#!/bin/bash
# ============================================================================
# TOD-Zero: Multi-turn Self-Play for Task-Oriented Dialogue
# ============================================================================
# Trains a customer service agent from scratch using only API schemas and a
# target domain — zero human-annotated dialogues required.
#
# Usage:
#   bash run.sh                          # defaults below
#   DOMAIN=airline bash run.sh
#   ITERATIONS=3 N_SCENARIOS=500 bash run.sh
#
# See TAU_BENCH_README.md for full documentation.
# ============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# Configuration — override any of these via environment variables
# ─────────────────────────────────────────────────────────────────────────────
source /shared/storage-01/setenv.sh
# Base model used to initialize Challenger, Solver, and User Simulator
BASE_MODEL=${BASE_MODEL:-"Qwen/Qwen2.5-0.5B-Instruct"}

# tau2-bench domain: retail | airline | telecom
DOMAIN=${DOMAIN:-"airline"}

# Number of self-play iterations (challenger→scenarios→solver→repeat)
ITERATIONS=${ITERATIONS:-5}

# User goals generated by the challenger per iteration
N_SCENARIOS=${N_SCENARIOS:-1000}

# Training duration per iteration
CHALLENGER_EPOCHS=${CHALLENGER_EPOCHS:-30}   # epochs to train the challenger
SOLVER_EPOCHS=${SOLVER_EPOCHS:-50}           # epochs to train the solver

# User simulator — fixed throughout, never trained
# GPU 3 is reserved for user sim; solver uses GPUs 0-2
USER_SIM_MODEL=${USER_SIM_MODEL:-"$BASE_MODEL"}
USER_SIM_PORT=${USER_SIM_PORT:-8000}
USER_SIM_GPU=3

# W&B
export WANDB_PROJECT=${WANDB_PROJECT:-"tod-zero-${DOMAIN}"}
export HF_HOME=${HF_HOME:-}
export WANDB_API_KEY=${WANDB_API_KEY:-}
export WANDB_DIR=${WANDB_DIR:-}

# ─────────────────────────────────────────────────────────────────────────────
# Launch
# ─────────────────────────────────────────────────────────────────────────────
BASE_MODEL=$BASE_MODEL \
DOMAIN=$DOMAIN \
ITERATIONS=$ITERATIONS \
N_SCENARIOS=$N_SCENARIOS \
CHALLENGER_EPOCHS=$CHALLENGER_EPOCHS \
SOLVER_EPOCHS=$SOLVER_EPOCHS \
USER_SIM_MODEL=$USER_SIM_MODEL \
USER_SIM_PORT=$USER_SIM_PORT \
USER_SIM_GPU=$USER_SIM_GPU \
bash examples/gigpo_trainer/run_tod_zero.sh
